name: Soulfire Dedicated Server

on:
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Java 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'microsoft'

    - name: Run Soulfire Server
      run: |
        curl -L https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-unknown-linux-musl.tar.gz | tar -xz
        ./bore local 38765 --to bore.pub &
        sleep 5
        java -jar SoulFireDedicated
