name: Soulfire Dedicated Server

on:
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up Java 25
      uses: actions/setup-java@v4
      with:
        java-version: '25'
        distribution: 'microsoft'

    - name: Install Cloudflared
      run: |
        curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
        chmod +x cloudflared

    - name: Run Soulfire Server
      run: |
        ./cloudflared tunnel --url http://localhost:38765 --no-autoupdate &
        sleep 10
        java -jar "SoulFireDedicated-2.7.0.jar"
